# Generated by Django 2.2.4 on 2019-08-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=1024)),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('data', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('referrer', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'アクセス履歴（access_logs）',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('RestAPI', 'REST API'), ('BGJob', 'Back Ground Job'), ('Etc', 'その他')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PROCESS管理（Process）',
            },
        ),
        migrations.CreateModel(
            name='Process_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField()),
                ('process_name', models.CharField(blank=True, max_length=100, null=True)),
                ('process_type', models.CharField(blank=True, max_length=20, null=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('I', 'Infomation'), ('W', 'Warning'), ('E', 'Error'), ('C', 'Critical')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_log', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name_plural': 'PROCESS実行履歴（Process_logs）',
            },
        ),
    ]
