from apps.ds.models.kitone_key import *
from apps.ds.models.customer import *
from apps.ds.models.anken import *
from apps.ds.models.history import *
from apps.ds.models.employee import *
from apps.ds.models.anken_advice import *
from apps.ds.models.anken_near import *
from apps.ds.models.anken_successrt_cmt import *
from apps.ds.models.anken_successrt_history import *
from apps.ds.models.anken_successrt import *
from apps.ds.models.customer_news import *
from apps.ds.models.keyword import *
from apps.ds.models.dictionary import *
from apps.ds.models.dictionary_synonym import *
from apps.ds.models.rulebook import *
from apps.ds.models.rulebook_condition import *
from apps.ds.models.code_name import *
from apps.ds.models.anken_karte_dispconfig import *
