# Generated by Django 2.2.4 on 2019-08-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('ds', '0002_auto_20190817_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebook',
            name='condition_where',
            field=models.TextField(blank=True, null=True, verbose_name='条件内容'),
        ),
        migrations.AlterField(
            model_name='rulebook',
            name='ruletype',
            field=models.SmallIntegerField(choices=[(1, 'アドバイス'), (2, 'アラート')], verbose_name='ルールタイプ'),
        ),
        migrations.CreateModel(
            name='Rulebook_Condition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lock_id', models.IntegerField(default=0, verbose_name='LOCK ID')),
                ('rulebook_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ルール名')),
                ('no', models.SmallIntegerField(verbose_name='条件No')),
                ('conditiontype', models.SmallIntegerField(choices=[(0, '先頭条件'), (1, 'AND条件'), (2, 'OR条件')], verbose_name='条件タイプ')),
                ('item_id', models.IntegerField(verbose_name='項目ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='項目名称')),
                ('item_type', models.SmallIntegerField(choices=[(1, '文字'), (2, '数字')], verbose_name='項目タイプ')),
                ('item_val', models.TextField(blank=True, null=True, verbose_name='項目値')),
                ('cmpr_type', models.SmallIntegerField(choices=[(1, '等しい'), (2, '等しくない'), (3, '以上'), (4, '以下'), (5, 'より大きい'), (6, 'より小さい'), (7, '含む'), (8, '含まない')], verbose_name='比較タイプ')),
                ('rulebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ds.Rulebook', verbose_name='ルールブック管理ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant')),
            ],
            options={
                'verbose_name_plural': 'ルールブック（ds_rulebook_condition）',
                'db_table': 'ds_rulebook_condition',
                'unique_together': {('tenant', 'rulebook', 'no')},
            },
        ),
        migrations.CreateModel(
            name='Dictionary_Synonym',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lock_id', models.IntegerField(default=0, verbose_name='LOCK ID')),
                ('dictionary_grpname', models.CharField(blank=True, max_length=200, null=True, verbose_name='辞書グループ名')),
                ('dictionary_distword', models.CharField(blank=True, max_length=200, null=True, verbose_name='辞書キーワード')),
                ('no', models.SmallIntegerField(verbose_name='類似ワードNo')),
                ('synonymword', models.CharField(max_length=200, verbose_name='類似ワード')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ds.Dictionary', verbose_name='辞書管理ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant')),
            ],
            options={
                'verbose_name_plural': '辞書（ds_dictionary_synonym）',
                'db_table': 'ds_dictionary_synonym',
                'unique_together': {('tenant', 'dictionary', 'no')},
            },
        ),
        migrations.CreateModel(
            name='Code_Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lock_id', models.IntegerField(default=0, verbose_name='LOCK ID')),
                ('code', models.CharField(max_length=20, verbose_name='コード')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='コード名称')),
                ('item_id', models.IntegerField(verbose_name='項目ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='項目名称')),
                ('item_type', models.SmallIntegerField(choices=[(1, '文字'), (2, '数字')], verbose_name='項目タイプ')),
                ('item_val', models.TextField(blank=True, null=True, verbose_name='項目値')),
                ('item_val2', models.TextField(blank=True, null=True, verbose_name='項目値その2')),
                ('item_val3', models.TextField(blank=True, null=True, verbose_name='項目値その3')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant')),
            ],
            options={
                'verbose_name_plural': 'コード名称（ds_code_name）',
                'db_table': 'ds_code_name',
                'unique_together': {('tenant', 'code', 'item_id')},
            },
        ),
    ]
