# Generated by Django 2.2.4 on 2019-08-20 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ds', '0003_auto_20190820_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anken_Karte_DispConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lock_id', models.IntegerField(default=0, verbose_name='LOCK ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ユーザー名')),
                ('dispno', models.SmallIntegerField(verbose_name='表示No')),
                ('item_id', models.IntegerField(verbose_name='項目ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='項目名称')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー管理ID')),
            ],
            options={
                'verbose_name_plural': '案件カルテ表示設定（ds_anken_karte_dispconfig）',
                'db_table': 'ds_anken_karte_dispconfig',
                'unique_together': {('tenant', 'user', 'dispno')},
            },
        ),
    ]
