# Generated by Django 2.2.4 on 2019-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0004_anken_karte_dispconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary_synonym',
            options={'verbose_name_plural': '辞書類似ワード（ds_dictionary_synonym）'},
        ),
        migrations.AlterModelOptions(
            name='rulebook_condition',
            options={'verbose_name_plural': 'ルールブック条件（ds_rulebook_condition）'},
        ),
        migrations.AddField(
            model_name='anken',
            name='result_kbn',
            field=models.SmallIntegerField(default=0, help_text='0:未案件,1:継続,2:成約,3:敗戦', verbose_name='結果区分'),
        ),
    ]
