# Generated by Django 2.2.4 on 2019-08-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0006_anken_near_anken_result_kbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_news',
            name='news_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='anken_near',
            name='anken_result_kbn',
            field=models.SmallIntegerField(default=0, help_text='2:成約,3:敗戦', verbose_name='結果区分'),
        ),
    ]
