# Generated by Django 2.2.4 on 2019-08-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0007_auto_20190824_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulebook_condition',
            name='rulebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulecons', to='ds.Rulebook', verbose_name='ルールブック管理ID'),
        ),
    ]
